ekansa/open-context-py

opencontext_py/settings.py
opencontext_py/wsgi.py

Developed through hours and hours of trial and error, and lots and lots
of Stackechange

Updates to help in deployment

---

.gitignore
opencontext_py/edit-wsgi.py

Ignore wsgi.py

---

opencontext_py/settings.py

Trying better static file management

---

change-secrets.json

Need to set this for deployment

Added missing key for secrets.json

---

opencontext_py/apps/searcher/solrsearcher/models.py
opencontext_py/apps/searcher/solrsearcher/regions.py

Fixed bug in unlimited facet fields

---

opencontext_py/apps/searcher/solrsearcher/makejsonld.py
opencontext_py/apps/searcher/solrsearcher/models.py

For queries and for sharing links to paging results

Added paging

---

opencontext_py/apps/searcher/solrsearcher/makejsonld.py
opencontext_py/apps/searcher/solrsearcher/records.py
opencontext_py/apps/searcher/solrsearcher/regions.py

some namespace cleanup

---

opencontext_py/apps/searcher/sets/views.py
opencontext_py/apps/searcher/solrsearcher/makejsonld.py
opencontext_py/apps/searcher/solrsearcher/templating.py
opencontext_py/templates/sets/content.html
opencontext_py/templates/sets/facets.html
opencontext_py/templates/sets/head.html
opencontext_py/templates/sets/view.html

Just starting to get facets to show, lots more to do.

Start of search human interface

---

opencontext_py/apps/ldata/linkannotations/equivalence.py
opencontext_py/apps/ldata/linkannotations/recursion.py
opencontext_py/apps/ocitems/assertions/math.py
opencontext_py/apps/searcher/solrsearcher/querymaker.py

Fixed a big discovered in a live demo (of course) involving numeric
hierarchy fields.

Bug fix numeric search, hierarchies

---

opencontext_py/apps/searcher/solrsearcher/makejsonld.py

Allow partial matches of filter links for numeric and date fields

Better filter link creation

---

opencontext_py/apps/searcher/solrsearcher/makejsonld.py
opencontext_py/apps/searcher/solrsearcher/models.py
opencontext_py/apps/searcher/solrsearcher/templating.py
opencontext_py/templates/sets/facets-alt.html
opencontext_py/templates/sets/facets.html
static/oc/css/general.css

API and HTML view that's no longer totally embarrassing.

Faceted search updates

---

opencontext_py/apps/searcher/solrsearcher/chronology.py
opencontext_py/apps/searcher/solrsearcher/makejsonld.py
opencontext_py/apps/searcher/solrsearcher/models.py
opencontext_py/apps/searcher/solrsearcher/querymaker.py
opencontext_py/apps/searcher/solrsearcher/records.py
opencontext_py/libs/chronotiles.py

Will check with an optimized index. Not sure if this works.

First attempt at adding chronology

---

opencontext_py/apps/searcher/solrsearcher/makejsonld.py
opencontext_py/apps/searcher/solrsearcher/responsetypes.py

Provides flexibility in turning it on or off

Added chrono-facet as responsetype

---

opencontext_py/apps/searcher/solrsearcher/chronology.py

To enable one to drill down into a selected tile.

Constrain chrono facets by selected tile

---

opencontext_py/apps/searcher/solrsearcher/templating.py
opencontext_py/settings.py
opencontext_py/templates/sets/content.html
opencontext_py/templates/sets/facet-option.html
opencontext_py/templates/sets/facets.html
static/oc/css/general.css

Facet search human view

---

opencontext_py/apps/searcher/solrsearcher/models.py
opencontext_py/apps/searcher/solrsearcher/querymaker.py

Enable quoted string searches

---

opencontext_py/apps/searcher/solrsearcher/records.py
opencontext_py/apps/searcher/solrsearcher/templating.py

So as not to get confused with predicates in declared namespaces

GeoJSON record props changes

---

opencontext_py/apps/searcher/solrsearcher/records.py

Result index

---

opencontext_py/apps/ocitems/identifiers/merritt/idassociate.py

Useful for interrupted processes

Allow adding of ids after a row

---

opencontext_py/apps/searcher/solrsearcher/filterlinks.py
opencontext_py/apps/searcher/solrsearcher/querymaker.py

Simplified, streamlined, more forgiving. No longer need to know the
parent item in a hierarchy.
Needs testing, but so far so good!

Search updates for new Solr schema

---

opencontext_py/apps/searcher/solrsearcher/chronology.py
opencontext_py/apps/searcher/solrsearcher/filters.py
opencontext_py/apps/searcher/solrsearcher/models.py
opencontext_py/apps/searcher/solrsearcher/querymaker.py
opencontext_py/apps/searcher/solrsearcher/specialized.py

Includes specialized responses for tDAR subject entitties

Search API for Dublin Core metadata

---

json-ld-examples/Item-context.json
json-ld-examples/Search-context.json
opencontext_py/apps/contexts/models.py
opencontext_py/apps/contexts/tests.py
opencontext_py/apps/contexts/views.py
opencontext_py/apps/indexer/solrdocument.py
opencontext_py/apps/ocitems/ocitem/models.py
opencontext_py/apps/ocitems/ocitem/templating.py
opencontext_py/apps/searcher/solrsearcher/makejsonld.py
opencontext_py/urls.py

Reduces a great deal of redundancy and bloat in the JSON-LD APIs.

Reference JSON-LD context objects by URIs

---

opencontext_py/apps/searcher/sets/views.py
opencontext_py/templates/edit/head.html
opencontext_py/templates/sets/content.html
opencontext_py/templates/sets/head.html
static/oc/js/numeric-styling.js
static/oc/js/search-mapping.js

For faceted search. First iteration.

Initial mapping of geospatial regions

---

opencontext_py/apps/searcher/solrsearcher/querymaker.py
opencontext_py/apps/searcher/solrsearcher/statsquery.py

Now inclusive, not ignoring outliers. Also bug fix

Range facet enhancements

---

opencontext_py/templates/sets/facet-option.html
opencontext_py/templates/sets/facets.html
opencontext_py/templates/sets/filter.html
opencontext_py/templates/sets/filters.html
static/oc/css/general.css

Made selected filter box with smaller text, better formatted. Also made
facet options have better borders.

Search style refinements

---

static/oc/js/search-mapping.js

Still lots to do to improve interactions

Better map boundary fitting

---

opencontext_py/templates/sets/head.html
static/oc/js/mapping/oc-easy-button.js
static/oc/js/mapping/oc-zoombox.css
static/oc/js/mapping/oc-zoombox.js
static/oc/js/oc-utilities.js
static/oc/js/search-mapping.js

Now can do a bounding box query from the map interface!

Bounding box interface, region button org

---

opencontext_py/apps/searcher/solrsearcher/geojsonregions.py

Avoiding unending recursion for aggregating geotiles

Important bug fix

---

opencontext_py/apps/ldata/linkannotations/recursion.py
opencontext_py/apps/ocitems/manifest/models.py

Limits recursion error for item indexing.

Fixing recursion error in indexing

---

opencontext_py/apps/ocitems/mediafiles/models.py

Merritt has some super long URL sizes.

Long URL sizes

---

opencontext_py/apps/ldata/orcid/api.py
opencontext_py/apps/ocitems/ocitem/models.py
opencontext_py/apps/ocitems/ocitem/templating.py
opencontext_py/apps/ocitems/persons/views.py
opencontext_py/templates/items/context.html
opencontext_py/templates/persons/view.html

Still need to add API calls to ORCID

Views of People and Organizations

---

opencontext_py/apps/ldata/orcid/api.py
opencontext_py/apps/ocitems/ocitem/templating.py
opencontext_py/templates/items/head.html
opencontext_py/templates/persons/view.html
static/oc/js/apis/orcid.js

Basic ORCID-API AJAX request

---

opencontext_py/templates/items/observations.html

now going to '/search/' not '/sets/'

Updated related search

---

opencontext_py/templates/media/view.html

Responsive preview size

---

opencontext_py/templates/index/view.html

Fixed index page map API request URL

---

opencontext_py/apps/exports/exptables/views.py
opencontext_py/urls.py

Until we get the table search functions done

Temporary table holding page

---

opencontext_py/templates/404.html

So the right footer is displayed

Better CSS / head for 404 error

---

opencontext_py/templates/index/robots.txt

Duh. Finally checked it with online tools

Better robots.txt paging

---

opencontext_py/apps/searcher/solrsearcher/filters.py
opencontext_py/apps/searcher/solrsearcher/specialized.py

For searches involving DINAA cross referencing

Fixed labeling of tDAR in dc-subjects metadata

---

opencontext_py/apps/ldata/linkvocabularies/views.py
opencontext_py/templates/vocabularies/head.html
opencontext_py/templates/vocabularies/index.html
opencontext_py/templates/vocabularies/outer-page.html
opencontext_py/templates/vocabularies/temp.html
opencontext_py/urls.py

Show a little information about controlled vocabularies that are part of
Open Context

Temporary vocab pages

---

opencontext_py/apps/entities/entity/views.py

or DAI, takes time to complete request

Added longer proxy timeout

---

opencontext_py/apps/searcher/search/views.py
opencontext_py/templates/search/geo-records.html
opencontext_py/templates/search/paging.html
opencontext_py/templates/search/search-modal.html
static/oc/js/exports/README.txt
static/oc/js/exports/csv-exporter.js
static/oc/js/oc-utilities.js
static/oc/js/search-mapping.js

Javascript for managing bulk exports from Open Context

Testing CSV + GeoJSON export client

---

opencontext_py/apps/entities/entity/templating.py
opencontext_py/apps/ldata/linkannotations/equivalence.py
opencontext_py/apps/ldata/linkannotations/recursion.py
opencontext_py/apps/ocitems/assertions/math.py
opencontext_py/apps/ocitems/assertions/sorting.py
opencontext_py/apps/searcher/search/views.py
opencontext_py/apps/searcher/solrsearcher/filterlinks.py
opencontext_py/apps/searcher/solrsearcher/filters.py
opencontext_py/apps/searcher/solrsearcher/geojsonrecords.py
opencontext_py/apps/searcher/solrsearcher/makejsonld.py
opencontext_py/apps/searcher/solrsearcher/memorycache.py
opencontext_py/apps/searcher/solrsearcher/models.py
opencontext_py/apps/searcher/solrsearcher/querymaker.py
opencontext_py/apps/searcher/solrsearcher/reconciliation.py
opencontext_py/apps/searcher/solrsearcher/recordprops.py
opencontext_py/apps/searcher/solrsearcher/uuids.py
opencontext_py/libs/memorycache.py

Cache database queries in memory, reduces database calls to 1 /5 of previous approach.

Search / query performance improvements

---

opencontext_py/apps/contexts/models.py
opencontext_py/apps/oai/models.py
opencontext_py/apps/searcher/solrsearcher/complete.py
opencontext_py/apps/searcher/solrsearcher/models.py
opencontext_py/libs/memorycache.py

So as not to mess up Nginx configurations

OAI without HTTP API requests

---

opencontext_py/apps/oai/models.py

More complete implementation of avoiding making an internal HTTP request

OAI-PMH bug fix

---

opencontext_py/apps/oai/models.py

We hates it precious, we hates it!

More fixing OAI-PMH memory leak

---

opencontext_py/apps/oai/models.py
opencontext_py/apps/ocitems/assertions/containment.py
opencontext_py/apps/ocitems/ocitem/models.py

So we don't automatically turn off caching in a lame way!

Cache fixes

---

opencontext_py/apps/ocitems/ocitem/models.py
opencontext_py/settings.py

Gets authorship, licensing for projects cached

Better OCitems caching

---

opencontext_py/apps/oai/views.py

Lame, but it seems it's part of the spec.

Support POST for OAI-PMH

---

opencontext_py/apps/oai/models.py

In response to very picky validation test results here:
https://www.openarchives.org/Register/ValidateSite

OAI-PMH improvements

---

opencontext_py/apps/searcher/solrsearcher/filters.py
opencontext_py/apps/searcher/solrsearcher/makejsonld.py
opencontext_py/apps/searcher/solrsearcher/querymaker.py
opencontext_py/apps/searcher/solrsearcher/recordprops.py
opencontext_py/libs/memorycache.py

conflicting caching of containment relations in faceted search

Bug fix: Redis cache problem for search

---

opencontext_py/apps/ocitems/ocitem/models.py

Missing predicate string key bug fixed

Fixed rare bug in item json-ld generation

---

opencontext_py/apps/ocitems/ocitem/models.py

Better bug fix for item json-ld generation

---

opencontext_py/apps/searcher/solrsearcher/requestdict.py

Added more troublesome bots for herding

---

opencontext_py/apps/searcher/search/views.py
opencontext_py/apps/searcher/solrsearcher/models.py
opencontext_py/apps/searcher/solrsearcher/requestdict.py
opencontext_py/libs/databasecache.py

Attempt to herd bots so they have limited ability to execute faceted
search queries but also support caching.

Search caching to handle bots better

---

opencontext_py/apps/entities/redirects/manage.py
opencontext_py/apps/entities/redirects/models.py
opencontext_py/apps/entities/redirects/views.py
opencontext_py/apps/exports/exptables/views.py
opencontext_py/settings.py

So as to redirect legacy URLs to better new ones

Added a simple URL redirection map

---

opencontext_py/apps/exports/exptables/templating.py

For rare cases with items don't have labels

Fixed citation error in table

---

opencontext_py/apps/exports/exptables/manage.py

So as to auto create and / or auto update metadata or a specific table.
This will get changed as we re-architect more complex assertions.

Method to create + overwrite metadata for table

---

opencontext_py/apps/exports/exptables/manage.py
opencontext_py/apps/exports/exptables/templating.py

Save metadata and use with the template to make JSON-LD and HTML

Use link_annotations for export table metadata

---

opencontext_py/templates/about/index.html

To the higher resolution version

Updated OC video link

---

opencontext_py/templates/about/index.html

Not needed, added to the Wistia settings

Remove the superfluous

---

opencontext_py/apps/exports/exptables/create.py
opencontext_py/apps/ocitems/editorials/manage.py
opencontext_py/apps/ocitems/editorials/models.py
opencontext_py/apps/ocitems/editorials/views.py
opencontext_py/settings.py

Ran into a case where we needed to redact data records because of
editorial policy concern. This model records the editorial action and
reason, and saves data for restoration if needed.

Added editorial model, redaction action

---

opencontext_py/apps/exports/exprecords/models.py

Easier to manage creation deletion without sequetial record order

Export table schema change

---

opencontext_py/apps/ldata/ansochre/api.py
opencontext_py/apps/ldata/linkentities/models.py
opencontext_py/apps/ldata/linkentities/web.py

Simple methods to get labels from the ANS OCHRE API. This is sorta
"brittle" in the sense that it treats JSON-LD as json, but it works.

ANS OCHRE API support

---

opencontext_py/apps/ocitems/ocitem/models.py
opencontext_py/apps/ocitems/ocitem/templating.py
opencontext_py/apps/searcher/solrsearcher/recordprops.py
opencontext_py/libs/rootpath.py

Changes http:// to https:// for links to media files.

HTTPS support for media file links

---

opencontext_py/settings.py

Add HTTPS header instruction

---

static/oc/js/datavis/types.js

Thanks to Sarah Rowe  (@sarahmrowe) for help!!

Fixed length problem with the rows, active row

---

opencontext_py/apps/ldata/pelagios/graph.py

Need this because of crazy Merritt image file uris

URI validation for Pelagios depictions

---

opencontext_py/apps/ldata/pelagios/graph.py

Changed annotations URI structure

---

opencontext_py/templates/about/services-querymeta.html
static/oc/js/tab-link.js

Also function for changing tabs

Summary chronology documentation

---

opencontext_py/apps/searcher/solrsearcher/makejsonld.py

Big Bug fix on temporal metadata in search

---

opencontext_py/apps/ldata/pelagios/graph.py
opencontext_py/apps/ldata/pelagios/models.py

Guided by recommendations on the use of ISO 8601 date ranges here:
https://github.com/pelagios/pelagios-cookbook/wiki/Joining-Pelagios

Temporal metadata added to Pelagios

---

opencontext_py/apps/ldata/linkannotations/recursion.py

Allows us to specify a path of parent items.

Sorting of concept hierarchies

---

static/oc/js/mapping/oc-zoombox.js
static/oc/js/search-mapping.js

for some reason, it is not working.

turning off zoom tile control

---

opencontext_py/apps/searcher/solrsearcher/querymaker.py

Trying to identify a bg causing restart and slowdown

Debugging solr queries

---

opencontext_py/apps/ldata/pelagios/gazetteer.py
opencontext_py/apps/ldata/pelagios/gazgraph.py
opencontext_py/apps/ldata/pelagios/models.py
opencontext_py/apps/ldata/pelagios/views.py
opencontext_py/urls.py

Sites that are referenced by collections outside of Open Context are
output in a list of RDF assertions, to hopefully conform to the Pelagios
gazetteer interchange format.

Pelagios gazetteer interchange data

---

opencontext_py/apps/ldata/tdar/api.py
opencontext_py/apps/ldata/tdar/dinaalink.py

So as to feed the Pelagios beast with gazetteer annotations linking to
Open Context

Cache tDAR items related to DINAA URIs

---

opencontext_py/apps/ldata/pelagios/serialize.py

so live site doesn't have as much

reduce prints for pelagios file caching

---

opencontext_py/apps/searcher/search/views.py
opencontext_py/apps/searcher/solrsearcher/querymaker.py

memory cache project map for home page

---

opencontext_py/apps/entities/entity/models.py
opencontext_py/apps/ocitems/ocitem/templating.py
opencontext_py/apps/searcher/solrsearcher/querymaker.py

Adds a search option to look in a parent project facet field if a
project has a parent project

Fixed solr query bug for child projects

---

opencontext_py/settings.py
opencontext_py/templates/footer.html
opencontext_py/templates/items/project.html
opencontext_py/templates/search/paging.html
opencontext_py/urls.py

Removed deprecated settings, fixed templating language, updated URL
patterns. Test first on DAI instance before moving to production.

Major upgrade for Django 1.10

---

opencontext_py/settings.py

makes the server hang. I guess use google analytics?

Disable metrics on client requests

---

opencontext_py/templates/about/terms.html

Based on comments emailed by S. Yerka

Typo fixes and clarifications to Terms

---

opencontext_py/apps/ocitems/mediafiles/internetarchive.py
opencontext_py/apps/ocitems/ocitem/templating.py
opencontext_py/templates/media/iiif.html

Feels odd to do this as civilization comes unraveled.

IIIF updates

---

opencontext_py/apps/contexts/models.py
opencontext_py/apps/indexer/solrdocument.py
opencontext_py/apps/ocitems/ocitem/models.py
opencontext_py/apps/ocitems/ocitem/templating.py
opencontext_py/apps/ocitems/octypes/supplement.py
opencontext_py/apps/ocitems/subjects/supplement.py
opencontext_py/apps/searcher/solrsearcher/makejsonld.py

Still need to test to make sure I didn't introduce any bugs

Added official GeoJSON-LD context, namespace

---

opencontext_py/apps/searcher/solrsearcher/querymaker.py

Bug fix, OR needed not AND in DC-Terms queries

---

opencontext_py/apps/searcher/solrsearcher/chronology.py
opencontext_py/templates/search/chrono-chart.html
static/oc/js/datavis/chrono-chart.js

Better exlusions of chrono-facets that go beyond an excluded date range
(legit, too, because of prior elimination of indexed facets that fall
out of a requested chronological scope).

Chronology improved behaviors

---

opencontext_py/apps/searcher/search/views.py
static/oc/js/datavis/chrono-chart.js
static/oc/js/search-mapping.js

Defaults to a visible chrono-chart, depending on some search filters.

Make chrono chart visible

---

opencontext_py/apps/searcher/solrsearcher/specialized.py

Fixed DINAA trinomial reconcile

---

opencontext_py/templates/search/chrono-chart.html
static/oc/js/datavis/chrono-chart.js

Simpler, more appropriate Y calculation

Chart improvements

---

static/oc/js/datavis/chrono-chart.js

Exterior lines with more contrast

Minor color tweeks for chrono charts

---

opencontext_py/apps/indexer/solrdocument.py

Related document index fixing

---

.gitignore
change-secrets.json
file_cache/README.txt
opencontext_py/apps/searcher/search/views.py
opencontext_py/settings.py

Prevents cache evictions by keeping faceted search results in a seperate
cache.

File Caching for Search Results

---

opencontext_py/apps/ldata/pelagios/graph.py
opencontext_py/apps/ldata/pelagios/models.py

Better handeling of gazetteer linked Open Context resources (in project
0) that link with project specific resources.

Improved pelagios data generation

---

opencontext_py/apps/ldata/linkentities/models.py

Getty Thesaurus of Geographic Names

New vocavulary slug creator to support

---

opencontext_py/templates/tables/sample-rows.html

Added horzontal scroll to top of tables

---

opencontext_py/apps/searcher/solrsearcher/models.py

Only do so if we're looking only in a specific item type

Fix for single project property check.

---

opencontext_py/apps/searcher/search/views.py
opencontext_py/apps/searcher/solrsearcher/models.py
opencontext_py/apps/searcher/solrsearcher/templating.py
opencontext_py/apps/searcher/solrsearcher/templatingfacets.py

We want to hide related facet options in the HTML if the user hasn't
selected an item_type to limit by.

Handling of related facet options

---

opencontext_py/apps/searcher/solrsearcher/chronology.py

Tweak minimum chrono tile count

---

opencontext_py/apps/ocitems/ocitem/models.py
opencontext_py/apps/ocitems/ocitem/templating.py
opencontext_py/apps/ocitems/projects/metadata.py
opencontext_py/apps/ocitems/projects/models.py
opencontext_py/templates/items/map.html

Now includes a mechanism for storing a note to display to public users
about geospatial data for projects. Useful for the DINAA project.

More flexible geo metadata for projects

---

static/oc/js/search-mapping.js

Again another DINAA map UI fix

Hide search map circle icon for low precision

---

opencontext_py/apps/edit/items/itemannotation.py
opencontext_py/apps/entities/entity/models.py
opencontext_py/apps/ldata/arachne/api.py
opencontext_py/apps/ldata/linkentities/models.py
opencontext_py/apps/ocitems/octypes/supplement.py

Now only done when we make a specific "skos:example" assocation to an
Arachne search

Fixed Arachne API calls

---

opencontext_py/apps/ldata/pelagios/models.py
opencontext_py/apps/ocitems/subjects/models.py

Simplified and more comprehensive.

Improved Pelagios Annotations exports

---

static/oc/js/datavis/chrono-chart.js

Set minimum width for a time span.

Chronology data vis improvement

---

.gitignore
opencontext_py/templates/media/3dhop.html
opencontext_py/templates/media/view.html

Attempt at 3Dhop integration

---

opencontext_py/templates/media/3dhop.html

Hopefully allow a wider range of rotation

Attempting a sphere trackball

---

opencontext_py/apps/about/views.py
opencontext_py/apps/exports/exptables/views.py
opencontext_py/apps/index/views.py
opencontext_py/apps/ocitems/documents/views.py
opencontext_py/apps/ocitems/mediafiles/views.py
opencontext_py/apps/ocitems/octypes/views.py
opencontext_py/apps/ocitems/persons/views.py
opencontext_py/apps/ocitems/predicates/views.py
opencontext_py/apps/ocitems/projects/views.py
opencontext_py/apps/ocitems/subjects/views.py
opencontext_py/apps/searcher/search/views.py
opencontext_py/libs/requestnegotiation.py

Better compliance with EU privacy protections, better privacy in general

Session flush for anonymous users

---

opencontext_py/apps/about/views.py
opencontext_py/apps/exports/exptables/views.py
opencontext_py/apps/index/views.py
opencontext_py/apps/ocitems/documents/views.py
opencontext_py/apps/ocitems/mediafiles/views.py
opencontext_py/apps/ocitems/octypes/views.py
opencontext_py/apps/ocitems/persons/views.py
opencontext_py/apps/ocitems/predicates/views.py
opencontext_py/apps/ocitems/projects/views.py
opencontext_py/apps/ocitems/subjects/views.py
opencontext_py/apps/searcher/search/views.py
opencontext_py/libs/requestnegotiation.py

TODO: test this works in a live deployment

Session cookie flushing

---

opencontext_py/apps/ocitems/ocitem/models.py

Bug fix for new media item primary key

---

opencontext_py/templates/items/project-content-nav.html

Use the slug, not uuid for project text search

Minor project search enhancement

---

opencontext_py/apps/ocitems/ocitem/templating.py
opencontext_py/templates/items/map.html
static/oc/js/mapping-rev/item-mapping.js

Individual items can now be seen on an overlay image

Added proj. map overlay images to item views

---

opencontext_py/apps/ocitems/projects/layers.py

Project geo-overlay caching

---

opencontext_py/apps/entities/entity/models.py
opencontext_py/apps/entities/entity/views.py
opencontext_py/tests/regression/entities/entity/test_entity.py

This updates the "entity search" API, which we mainly use internally (not for public users, though the API is publicly exposed). The main point of the API is make it easier get IDs for Open Context database entities while we're using Open Refine to prepare a dataset. It strictly queries the Postgres database, not Solr, because we want to check on entities for "works in progress" that may not yet be indexed in Solr.
It has a regression test (requires database access) that you can invoke with:
`pytest opencontext_py/tests/regression/entities -v -x --pdb`

Entity search fix

---

Pipfile.lock
sysadmin/build.yml
sysadmin/templates/start-no-db.sh.j2
sysadmin/templates/startup.sh.j2

[The killing/restarting of uwsgi is probably not correct · Issue #759 · ekansa/open-context-py](https://github.com/ekansa/open-context-py/issues/759)

Fixes #759: restarting of uwsgi is now correctly handled

---

opencontext_py/apps/contexts/readprojectcontext.py
opencontext_py/apps/entities/entity/views.py
opencontext_py/apps/indexer/solrdocumentnew.py
opencontext_py/apps/searcher/new_solrsearcher/configs.py
opencontext_py/apps/searcher/new_solrsearcher/querymaker.py
opencontext_py/apps/searcher/new_solrsearcher/ranges.py
opencontext_py/apps/searcher/new_solrsearcher/result_facets_nonpath.py
opencontext_py/apps/searcher/new_solrsearcher/result_facets_standard.py
opencontext_py/apps/searcher/new_solrsearcher/resultmaker.py
opencontext_py/apps/searcher/new_solrsearcher/searchfilters.py
opencontext_py/apps/searcher/new_solrsearcher/searchlinks.py
opencontext_py/apps/searcher/new_solrsearcher/searchsolr.py
opencontext_py/apps/searcher/new_solrsearcher/utilities.py
opencontext_py/apps/searcher/new_solrsearcher/views.py

Got all the normal facets to work. Now to do the geospatial and chronological facets.

Solr refactor 5

---

opencontext_py/apps/contexts/manage.py
opencontext_py/apps/contexts/projectcontext.py
opencontext_py/apps/imports/fieldannotations/types.py
opencontext_py/apps/imports/fields/create.py
opencontext_py/apps/indexer/solrdocumentnew.py
opencontext_py/apps/ocitems/assertions/sorting.py
opencontext_py/apps/ocitems/ocitem/generation.py
opencontext_py/apps/searcher/new_solrsearcher/configs.py
opencontext_py/apps/searcher/new_solrsearcher/querymaker.py
opencontext_py/apps/searcher/new_solrsearcher/result_facets_chronology.py
opencontext_py/apps/searcher/new_solrsearcher/result_facets_geo.py
opencontext_py/apps/searcher/new_solrsearcher/result_facets_nonpath.py
opencontext_py/apps/searcher/new_solrsearcher/result_records.py
opencontext_py/apps/searcher/new_solrsearcher/resultmaker.py
opencontext_py/apps/searcher/new_solrsearcher/searchfilters.py
opencontext_py/apps/searcher/new_solrsearcher/searchsolr.py
opencontext_py/apps/searcher/new_solrsearcher/utilities.py
opencontext_py/apps/searcher/new_solrsearcher/views.py
opencontext_py/libs/globalmaptiles.py
opencontext_py/tests/unit/searcher/new_solrsearcher/test_utilities.py

Finally got to the stage where we return individual result records from the refactored solr searches.

Solr refactor 6

---

opencontext_py/apps/ocitems/manifest/models.py

Fixes bug that prevents syncing

Fix save bug in legacy manifest model

---

opencontext_py/apps/ocitems/identifiers/ezid/ezid.py

@ekansa A fix to consider. Please remind me of whether there are tests that I should consider when issuing this request.

in parsing anvl, handle having colons in the metadata

---

Pipfile
opencontext_py/apps/etl/importer/transforms/reconcile.py
opencontext_py/apps/searcher/new_solrsearcher/configs.py
opencontext_py/apps/searcher/new_solrsearcher/db_entities.py
opencontext_py/apps/searcher/new_solrsearcher/result_records.py
opencontext_py/templates/bootstrap_vue/search/parts/exports.html

Updates to fix import bug, update python version, add string attributes to downloads

Main <- Staging

---

opencontext_py/templates/bootstrap_vue/search/parts/tabs.html

Mainly off world paths and querying fixes

Don't show off world map if we have results

---

opencontext_py/apps/all_items/editorial/archive/internet_archive_thumbnails.py
opencontext_py/apps/all_items/editorial/item/updater_manifest.py
opencontext_py/apps/indexer/index_new_schema.py

Minor updates for indexing, adding new subjects items with containment assertion

main<- Staging
