opencontext_py/apps/indexer/solrdocument.py
opencontext_py/apps/ocitems/ocitem/models.py
opencontext_py/apps/ocitems/ocitem/templating.py
opencontext_py/templates/items/citation.html
static/oc/css/general.css

Useful for citation and indexing. We're now including the dc-terms:title
in the document indexing (for full-text search).

Dublin-core title element + styling

---

opencontext_py/settings.py

Production sites handle static files differently

Change to help deployment

---

opencontext_py/settings.py

Allowed hosts can be added from reading the secrets.json file. This
keeps configuration and code more distinct. Makes it easier to update
changes (say with Git version control) without having to update local
configurations.

Remove local configuration from settings.py

---

opencontext_py/apps/entities/entity/models.py
opencontext_py/apps/searcher/solrsearcher/querymaker.py

Only linked data entities of type "property" should have different
handling in faceted search hierarchies.

Check linked data entity type for facet searches

---

opencontext_py/apps/searcher/solrsearcher/chronology.py

Aggregating facets counts aggregates the number of chronological
"events", not the number of solr documents!
No need for further debugging

Removed debugging code

---

opencontext_py/apps/searcher/solrsearcher/regions.py

So as not to make a tile region in the ocean off the coast of Africa for
missing data items

Don't display missing geodata

---

opencontext_py/apps/ocitems/ocitem/templating.py

Some searches return empty results, don't show the link if there is
nothing associated.

Enhancement: don't show tDAR link if no data

---

static/oc/js/mapping/oc-zoombox.js

Treat zoom levels as numbers, not strings

Minor bounding-box enhancement

---

requirements.txt

latest 'django-debug-toolbar' version is 1.4 not 1.4.1 [https://pypi.python.org/pypi/django-debug-toolbar]
latest 'redis' version is 2.10.5 not 2.1.5 [https://pypi.python.org/pypi/redis/2.10.5]

fixed typos in requirements.txt

---

opencontext_py/templates/about/head.html
opencontext_py/templates/edit/head.html
static/oc/js/tab-link.js

Since opencontext makes use of bootstrap tabs this might be useful for linking to specific tabs and stay on the tab after reloading the page.

linking to specific tab + stay on tab after reload

---

opencontext_py/apps/indexer/crawler.py
opencontext_py/apps/indexer/reindex.py
opencontext_py/apps/indexer/solrdocument.py
opencontext_py/apps/searcher/search/views.py
opencontext_py/apps/searcher/solrsearcher/filters.py
opencontext_py/apps/searcher/solrsearcher/makejsonld.py
opencontext_py/apps/searcher/solrsearcher/models.py
opencontext_py/apps/searcher/solrsearcher/querymaker.py

Add to indexing of media items by getting properties from related media
resources. Enables search based on properties that describe subjects
associated to media resources. This all about denormalizing the solr
index even more.

Media indexing: related subjects properties

---

opencontext_py/apps/searcher/search/views.py
opencontext_py/apps/searcher/solrsearcher/models.py
opencontext_py/apps/searcher/solrsearcher/requestdict.py

Reduce the overhead of bots crawling the faceted search by removing
facets from their view and stopping them from doing anything but paging
though requests

Simple Bot detection for faceted search

---

opencontext_py/apps/exports/exptables/manage.py
opencontext_py/apps/exports/exptables/models.py
opencontext_py/apps/ldata/linkannotations/models.py

Since we need to be able to edit export table metadata, it makes sense
to use more general Open Context modes / code, rather than reinvent the
wheel. However, export table metadata needs to be somewhat different, in
that it needs to record counts of object items. Therefore, this change
includes an extension to the link_annoations model so that we can add
extra information to the assertion. That extra information is in the
form of a JSON encoded dict object.
There's a method that we will include temporarily to migrate the
existing table metadata to the link_annotations table.

Better metadata management of export tables

---

opencontext_py/apps/searcher/solrsearcher/geojsonrecords.py
opencontext_py/apps/searcher/solrsearcher/recordprops.py
opencontext_py/apps/searcher/solrsearcher/uuids.py

Because we only index, not store string field data, we need to call the
database to support getting attribute data for string fields in the
Search API

Get string attribute data in Search API

---

opencontext_py/apps/ocitems/subjects/views.py
opencontext_py/urls.py

The first version of OC had badly designed URLs with ".php" in them.
This redirects links to the better designed current version

Redirect for first version of OC

---

opencontext_py/apps/ldata/pelagios/graph.py
pelagios-examples/pelagios-petra-example.ttl

Now the foaf:homepage points to the URI of the item with a gazetteer
annotation.

Update to Pelagios foaf:homepage

---

opencontext_py/apps/entities/entity/models.py
opencontext_py/apps/ldata/pelagios/gazannos.py
opencontext_py/apps/ldata/pelagios/gazetteer.py
opencontext_py/apps/ldata/pelagios/gazgraph.py
opencontext_py/apps/ldata/pelagios/graph.py
opencontext_py/apps/ldata/pelagios/views.py
opencontext_py/apps/ldata/pelagios/void.py

This provides Pelagios annotations in cases where Open Context is used
(or can function) as a gazetteer.

Pelagios Annotations where OC is the gazetteer

---

opencontext_py/apps/ldata/pelagios/graph.py
opencontext_py/apps/ldata/pelagios/projects.py
opencontext_py/apps/ldata/pelagios/serialize.py
opencontext_py/apps/ldata/pelagios/views.py
opencontext_py/settings.py
pelagios-examples/README.md
pelagios-examples/void.ttl

Because the database cache gets over-written, it is useful to cache data to a file.

Mainly file-caching of Pelagios outputs

---

opencontext_py/apps/searcher/solrsearcher/chronology.py
opencontext_py/apps/searcher/solrsearcher/makejsonld.py

A client may request to filter by date ranges, this will result in a
query result set that gives records filtered by ranges, but since items
can have multiple chronological events, metadata for later events will
still be returned by Solr. This filters such later chronological
metadata out.

Exclude chronotiles based on request

---

opencontext_py/apps/ocitems/documents/views.py
opencontext_py/apps/ocitems/mediafiles/views.py
opencontext_py/apps/ocitems/octypes/views.py
opencontext_py/apps/ocitems/persons/views.py
opencontext_py/apps/ocitems/predicates/views.py
opencontext_py/apps/ocitems/projects/views.py
opencontext_py/apps/ocitems/subjects/views.py
opencontext_py/apps/searcher/search/views.py
opencontext_py/libs/requestnegotiation.py

The "patch_vary_headers" makes sure that we keep different versions of
cached responses, depending on the "accept" header of the client. This
prevents HTML returned when a client wanted JSON.

Fixed content negotiation caching problem

---

opencontext_py/apps/ldata/pelagios/void.py

Hopefully, this will make it easier for Pelagios to injest the data
dumps listed in the Void file.

Add '.ttl' extenstion to void data dump

---

opencontext_py/apps/indexer/solrdocument.py

So as to avoid string casting errors.

More validation in indexing

---

opencontext_py/templates/about/people.html

Old link points to "http://ux.opencontext.org/blog" (404)

Fix link to Blog (Heritage Bytes)

---

opencontext_py/apps/about/views.py
static/oc/js/about/estimation.js

Hard to replicate permisions error with the estimation form. Use GET
instead of POST method to avoid, which is reasonable given that we're
just getting data not actually storing any (so OK for REST principles).

Estimation form fix

---

opencontext_py/templates/items/panel-title.html

Don't display link to a dynamic image if the item has a PDF document.

Bug fix for media panel

---

opencontext_py/libs/requestnegotiation.py

Not used except for human remain toggle.

Stop removal of session cookies

---

requirements.txt

because 0.1.19 breaks django-debug-toolbar as detailed in https://github.com/jazzband/django-debug-toolbar/issues/862

Update sqlparse from 0.1.19 to 0.2.4

---

opencontext_py/apps/ocitems/ocitem/templating.py

Use the preview if the preview has a GeoJSON mime type

Better legacy templating for GIS
